<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0cd3b2f6cef62692d8760dd31f152f2d
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'ParseCsv\\extensions\\' => 20,
            'ParseCsv\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ParseCsv\\extensions\\' => 
        array (
            0 => __DIR__ . '/..' . '/parsecsv/php-parsecsv/src/extensions',
        ),
        'ParseCsv\\' => 
        array (
            0 => __DIR__ . '/..' . '/parsecsv/php-parsecsv/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0cd3b2f6cef62692d8760dd31f152f2d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0cd3b2f6cef62692d8760dd31f152f2d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
